# Generated by Django 3.0.6 on 2020-06-01 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=20)),
                ('whatsapp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_menu', models.DateTimeField()),
                ('id_almuerzo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Menuapp.Almuerzo')),
                ('id_ensalada', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Menuapp.Ensalada')),
                ('id_postre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Menuapp.Postre')),
            ],
        ),
        migrations.CreateModel(
            name='Elegir_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menuapp.Empleado')),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menuapp.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menuapp.Empleado', unique=True)),
            ],
        ),
    ]
