# Generated by Django 3.0.6 on 2020-06-01 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menuapp', '0002_administrador_elegir_menu_empleado_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menuapp.Empleado'),
        ),
    ]
