# Generated by Django 3.0.6 on 2020-06-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menuapp', '0003_auto_20200601_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='whatsapp',
            field=models.CharField(max_length=20),
        ),
    ]
