# Generated by Django 3.0.6 on 2020-06-03 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menuapp', '0007_auto_20200603_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id_almuerzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Menuapp.Almuerzo'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id_ensalada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Menuapp.Ensalada'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id_postre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Menuapp.Postre'),
        ),
    ]
