# Generated by Django 3.0.6 on 2020-06-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menuapp', '0008_auto_20200603_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='elegir_menu',
            name='uuid',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
